# https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

string AUDIO_AAC='audio/aac'
string APPLICATION_X_ABIWORD='application/x-abiword'
string APPLICATION_X_FREEARC='application/x-freearc'
string VIDEO_X_MSVIDEO='video/x-msvideo'
string APPLICATION_VND_AMAZON_EBOOK='application/vnd.amazon.ebook'
string APPLICATION_OCTET_STREAM ='application/octet-stream'
string IMAGE_BMP='image/bmp'
string APPLICATION_X_BZIP='application/x-bzip'
string APPLICATION_X_BZIP2='application/x-bzip2'
string APPLICATION_X_CSH='application/x-csh'
string TEXT_CSS='text/css'
string TEXT_CSV='text/csv'
string APPLICATION_MSWORD='application/msword'
string APPLICATION_MSWORD_OPEN_XML='application/vnd.openxmlformats-officedocument.wordprocessingml.document'

# application/vnd.ms-fontobject
# application/epub+zip
# application/gzip
# image/gif
string TEXT_HTML='text/html'
# image/vnd.microsoft.icon
# text/calendar
# application/java-archive
string IMAGE_JPEG='image/jpeg'
string TEXT_JAVASCRIPT='text/javascript'
string APPLICATION_JSON='application/json'

# application/ld+json
# audio/midi
# audio/x-midi
# audio/mpeg
# video/mpeg
# application/vnd.apple.installer+xml
# application/vnd.oasis.opendocument.presentation
# application/vnd.oasis.opendocument.spreadsheet
# application/vnd.oasis.opendocument.text
# audio/ogg
# video/ogg
# application/ogg
# audio/opus
# font/otf
string IMAGE_PNG='image/png'
# application/pdf
# application/x-httpd-php
# application/vnd.ms-powerpoint
# application/vnd.openxmlformats-officedocument.presentationml.presentation
# application/vnd.rar
# application/rtf
# application/x-sh
# image/svg+xml
# application/x-shockwave-flash
# application/x-tar
# image/tiff
# video/mp2t
# font/ttf
string TEXT_PLAIN='text/plain'


# application/vnd.visio
# audio/wav
# audio/webm
# video/webm
# image/webp
# font/woff
# font/woff2
# application/xhtml+xml
# application/vnd.ms-excel
# pplication/vnd.openxmlformats-officedocument.spreadsheetml.sheet
# application/xml

string TEXT_XML='text/xml'

# application/vnd.mozilla.xul+xml
# application/zip
# video/3gpp
# audio/3gpp
# video/3gpp2
# audio/3gpp2
# application/x-7z-compressed
